param(
    [string]$PR_ID
)

Write-Host "Starting AI review for PR $PR_ID"

# Fetch PR diff
python prdiff.py $PR_ID

$diffFile = "pr_$PR_ID.diff"

if (!(Test-Path $diffFile)) {
    Write-Host "Diff file missing"
    exit 1
}

$diff = Get-Content $diffFile -Raw

# Remove noisy git metadata
$diff = $diff -replace "index .*",""
$diff = $diff -replace "--- .*",""
$diff = $diff -replace "\+\+\+ .*",""

# Split by file
$files = $diff -split "diff --git"

$chunkSize = 800
$chunkList = @()

foreach ($file in $files) {

    if ($file.Trim().Length -eq 0) { continue }

    $lines = $file -split "`n"

    for ($i=0; $i -lt $lines.Count; $i += $chunkSize) {

        $chunk = $lines[$i..([math]::Min($i+$chunkSize-1,$lines.Count-1))] -join "`n"
        $chunkList += $chunk

    }
}

Write-Host "Chunks created:" $chunkList.Count

$results = @()

$jobs = @()

foreach ($chunk in $chunkList) {

$prompt = @"
You are an expert enterprise code reviewer.

Languages may include:
COBOL
HLASM assembler
Java
Python
TypeScript
C++
Batch

Review the git diff.

Focus ONLY on:

• logic bugs
• null pointer risks
• incorrect conditions
• missing error handling
• security issues
• performance issues

Ignore style formatting.

Return short bullet points only.

DIFF:
$chunk
"@

    $jobs += Start-Job -ScriptBlock {

        param($prompt)

        $prompt | copilot -s -p -

    } -ArgumentList $prompt
}

Write-Host "Running parallel Copilot reviews..."

$jobs | Wait-Job

foreach ($job in $jobs) {

    $results += Receive-Job $job

}

Remove-Job $jobs

# Merge results
$reviewFile = "review_$PR_ID.md"

$final = @"
## AI Code Review

Pull Request: $PR_ID

---

$($results -join "`n")

---

Generated by Copilot CLI
"@

$final | Out-File $reviewFile -Encoding utf8

Write-Host "Posting review..."

python post_comment.py $PR_ID $reviewFile

Write-Host "Completed."
